# Generated by Django 5.2.15 on 2026-06-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_vote_two_scenarios_and_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prototype_interest', to='workshop.vote')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
